/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ddT7wfnzx79n44ty2Sa9LN
import * as React from "react";
import { EmbedCss } from "@plasmicpkgs/plasmic-embed-css";

export default function GlobalContextsProvider(props) {
  const { children, embedCssProps } = props;
  return (
    <EmbedCss
      {...embedCssProps}
      css={
        embedCssProps && "css" in embedCssProps ? embedCssProps.css : undefined
      }
    >
      {children}
    </EmbedCss>
  );
}
