/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ddT7wfnzx79n44ty2Sa9LN
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantsepPsfinF5Moi } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: EpPsfinF5moi/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsepPsfinF5Moi
});
